### ISSUE TITLE
Save Private Key with Enhanced Security on "Next" Action

### ISSUE THREAD

**Issue by JingYuan0926** [derek2403/near#21]
Currently, the wallet creation flow includes a name checker to verify if the wallet name exists, with the relevant code implemented and the seed phrase and private key securely hidden. The next step is to implement functionality where, upon pressing "Next," the private key will be securely saved, similar to how Metamask, Phantom, or other browser wallets handle it. This should include robust security measures to ensure the private key is encrypted and stored safely, protecting it from unauthorized access.

**Comment by derek2403** [comment]
Nice feature
