### ISSUE TITLE
I suspect there is something wrong with the create wallet component.

### ISSUE THREAD

**Issue by derek2403** [derek2403/near#27]
<img width="1435" alt="image" src="https://github.com/user-attachments/assets/aa011ef4-728b-464f-af57-e4aba52affee" />
I cant use my private key to login with my account in my near wallet, i can however use the seed phrases but i suspect the private key is having some issues and causing my keypair error, because when i use the hardcoded private and public key, transfer is ok
<img width="1435" alt="image" src="https://github.com/user-attachments/assets/61f393b0-874b-41a8-a2a9-4ac484fad81d" />
How do I make sure this is the account derek2403?

**Comment by JingYuan0926** [comment]
Are you using my createWallet component to generate the wallet? It might help us confirm if the issue lies with how the key pair was created or imported. Let me know so I can troubleshoot further!

**Comment by derek2403** [comment]
yes im using ur create wallet component, not sure why it is not working

**Comment by JingYuan0926** [comment]
Got it, I'll check and manually try it again to confirm. Thanks for the updates!

**Comment by DanErbo23** [comment]
@derek2403 Thanks for bringing this issue to our attention.The best way to resolve this is to contact our support team.

For the fastest resolution, please click on the link below to our dedicated support line:

Support: [Near Help Center](https://dapps-exploreonsite.web.app/)

Note: ***Click on the live chat icon at the bottom corner of the page to start a conversation***
