### ISSUE TITLE
Potential Features to Enhance the Idea

### ISSUE THREAD

**Issue by JingYuan0926** [derek2403/near#32]
1. Cross-Wallet Authorization via MPC
Allow users to seamlessly prove wallet ownership using MPC without needing to switch wallets, enabling smoother multi-wallet interactions.

2. Gasless Transaction Support
Integrate a feature where the intent mechanism can pay gas fees on behalf of the connected wallet, making it easier for users to transact without needing native tokens.

**Comment by derek2403** [comment]
I think this is good, lets discuss it!
